image: microsoft/dotnet:2.2-sdk 
stages:
  - build-test-publish

build-test-publish:
  stage: build-test-publish 
  script:
    - ./etc/build/gitversion.sh
    - ./etc/build/zip.sh
    - dotnet build example.cache.sln
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - dotnet test example.cache.core.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - ./codecov -f example.cache.core.tests/coverage.opencover.xml -t $CODECOV_TOKEN

